// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_post_blog/test/presentation/post/list/post_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_post_blog/domain/model/post_model.dart' as _i5;
import 'package:flutter_post_blog/domain/repository/post_repository.dart'
    as _i2;
import 'package:flutter_post_blog/domain/use_case/post/fetch_posts_use_case.dart'
    as _i3;
import 'package:flutter_post_blog/domain/use_case/post/watch_posts_use_case.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePostRepository_0 extends _i1.SmartFake
    implements _i2.PostRepository {
  _FakePostRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FetchPostsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchPostsUseCase extends _i1.Mock implements _i3.FetchPostsUseCase {
  MockFetchPostsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePostRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PostRepository);

  @override
  _i4.Future<List<_i5.PostModel>> call(_i3.FetchPostsUseCaseParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<List<_i5.PostModel>>.value(
              <_i5.PostModel>[],
            ),
          )
          as _i4.Future<List<_i5.PostModel>>);
}

/// A class which mocks [WatchPostsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchPostsUseCase extends _i1.Mock implements _i6.WatchPostsUseCase {
  MockWatchPostsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePostRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PostRepository);

  @override
  _i4.Stream<List<_i5.PostModel>> call(_i6.WatchPostsUseCaseParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Stream<List<_i5.PostModel>>.empty(),
          )
          as _i4.Stream<List<_i5.PostModel>>);
}
