// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_post_blog/test/domain/use_case/post/fetch_posts_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_post_blog/domain/model/post_model.dart' as _i2;
import 'package:flutter_post_blog/domain/repository/post_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePostModel_0 extends _i1.SmartFake implements _i2.PostModel {
  _FakePostModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PostModel>> getPosts({
    DateTime? startAfter,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {
              #startAfter: startAfter,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.PostModel>>.value(
              <_i2.PostModel>[],
            ),
          )
          as _i4.Future<List<_i2.PostModel>>);

  @override
  _i4.Stream<List<_i2.PostModel>> watchPosts({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#watchPosts, [], {#limit: limit}),
            returnValue: _i4.Stream<List<_i2.PostModel>>.empty(),
          )
          as _i4.Stream<List<_i2.PostModel>>);

  @override
  _i4.Future<_i2.PostModel> getPostById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPostById, [id]),
            returnValue: _i4.Future<_i2.PostModel>.value(
              _FakePostModel_0(this, Invocation.method(#getPostById, [id])),
            ),
          )
          as _i4.Future<_i2.PostModel>);

  @override
  _i4.Future<String> createPost({
    required String? title,
    required String? content,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #title: title,
              #content: content,
              #imageUrl: imageUrl,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createPost, [], {
                  #title: title,
                  #content: content,
                  #imageUrl: imageUrl,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> updatePost(_i2.PostModel? post) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [post]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePost(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
