// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  // TODO optional: hide somewhere gitignored.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQGB0UXye9xUjOd_1tLA8bD3SVo6grVsc',
    appId: '1:636830999690:web:d9b4151ad2cdef5aa07973',
    messagingSenderId: '636830999690',
    projectId: 'sample-post-blog',
    authDomain: 'sample-post-blog.firebaseapp.com',
    storageBucket: 'sample-post-blog.firebasestorage.app',
    measurementId: 'G-K2L6JBEVD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFGz8KilQOMIpjqcuWeYuezwfNoJnVSrE',
    appId: '1:636830999690:android:3f394251f1eac4b2a07973',
    messagingSenderId: '636830999690',
    projectId: 'sample-post-blog',
    storageBucket: 'sample-post-blog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXIrCNcPpAfOKzuPYc2ztlV1-UDzppEKQ',
    appId: '1:636830999690:ios:d78e1e3a101288e7a07973',
    messagingSenderId: '636830999690',
    projectId: 'sample-post-blog',
    storageBucket: 'sample-post-blog.firebasestorage.app',
    iosBundleId: 'com.example.flutterPostBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXIrCNcPpAfOKzuPYc2ztlV1-UDzppEKQ',
    appId: '1:636830999690:ios:d78e1e3a101288e7a07973',
    messagingSenderId: '636830999690',
    projectId: 'sample-post-blog',
    storageBucket: 'sample-post-blog.firebasestorage.app',
    iosBundleId: 'com.example.flutterPostBlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQGB0UXye9xUjOd_1tLA8bD3SVo6grVsc',
    appId: '1:636830999690:web:61d8bb791488ecaba07973',
    messagingSenderId: '636830999690',
    projectId: 'sample-post-blog',
    authDomain: 'sample-post-blog.firebaseapp.com',
    storageBucket: 'sample-post-blog.firebasestorage.app',
    measurementId: 'G-18Z21W9P6L',
  );
}
